Added compile switch for different hosts/OS'

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -10,7 +10,7 @@
 COMPILE_OPTS="productive"
 
 # Choose python version to compile for
-PY_VER="3.5"
+PY_VER="2.7"
 F2PY="f2py$PY_VER"
 PYTHON="python$PY_VER"
 
@@ -33,7 +33,16 @@ python_library="dynfor"
 fortran_library="libdynfor"
 pysig="${precc}/$python_library.pyf"
 
-LIBS='-L/usr/local/lib -lspherepack -lblas -llapack'
+host=`hostname -f`
+uname=`uname`
+if [ ${host: -6} == 'uib.no' ]; then
+	LIBS='-L/Data/gfi/users/local/lib -lspherepack -lblas -llapack'
+elif [ "$uname" == 'Darwin' ]; then
+	LIBS='-L/usr/local/lib -lspherepack -lblas -llapack'
+else
+	echo "Error: Unknown host/ operation system."
+	exit 1
+fi
 
 # TODO: Make code ready for -pedantic
 if [ "$COMPILE_OPTS" == 'productive' ]; then
